import type { Metadata } from "next";
import "@workspace/ui/styles/globals.css";
import { SidebarInset, SidebarProvider } from "@workspace/ui/components/sidebar"
import { AppSidebar } from "@/components/navigation/app-sidebar";
import React from "react";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { SiteHeader } from "@/components/navigation/site-header";


export const metadata: Metadata = {
    title: "Even Legion",
    description: "Generated by the TECH Team",
};

export default function RootLayout({ children } : {children: React.ReactNode}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <ThemeProvider
            attribute={'class'}
            defaultTheme={'system'}
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider
                style={
                    {
                        "--sidebar-width": "calc(var(--spacing) * 72)",
                        "--header-height": "calc(var(--spacing) * 12)",
                    } as React.CSSProperties
                }>
                <AppSidebar variant="inset" />
                <SidebarInset >
                    <SiteHeader />
                    <main>
                        {children}
                    </main>
                </SidebarInset>
            </SidebarProvider>
        </ThemeProvider>
        <Toaster/>
        </body>
        </html>
    )
}
