import type { Metadata } from "next";
import "@workspace/ui/styles/globals.css";
import { SidebarProvider, SidebarTrigger } from "@workspace/ui/components/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import React from "react";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
    title: "Even Legion",
    description: "Generated by the TECH Team",
};

export default function RootLayout({ children } : {children: React.ReactNode}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <ThemeProvider
            attribute={'class'}
            defaultTheme={'system'}
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                <AppSidebar />
                <main>
                    <SidebarTrigger />
                    {children}
                </main>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    )
}